[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+neon"]

[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-C", "target-cpu=cortex-a72", "-C", "target-feature=+neon"]
